myblog/blog/urls.py
from django.urls import path
from blog import views
# app이름 꼭 적어주기
app_name='blog'
urlpatterns = [
    path('',views.post_list,name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit', views.post_edit, name='post_edit'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

myblog/blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class Post(models.Model):
    # author는 사용자의 createsuperuser 혹은 superuser가 만든 계정자료와 연동
    # 'auth.User' 는 장고에서 말하는 admin 계정 class(자동생성됨) - id,pw,pk등등이 속성으로 있음
    # 계정은 여러개 만들 수 있음 : pk로 식별
    # author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    # on_delete = models.CASCADE(회원탈퇴하면 연동된 글들이 같이 지워짐)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    # CharField는 글자수 제한
    title = models.CharField(max_length=200)
    text = models.TextField()
    # 작성일, default = timezone.now(자동으로 서버시간이 들어감)
    created_date = models.DateTimeField(default = timezone.now)
    
    # 게시일(공개시간)
    # blank=True일 경우 컬럼이 비어있어도 됨,  null=True는 null값 넣기 허용
    published_date = models.DateTimeField(blank=True, null=True)
    
    # 게시하는 함수, self꼭 써줘야함 table에서 row하나(글(Post) 하나)를 뜻함
    # row하나를 self에 저장해서 수정뒤 반영
    def publish(self):
        self.published_date = timezone.now()
        # 수정하고 반영해줘야 함!!
        self.save()
    
    # admin에 보여질 정보를 models에서 정의해줘야함
    def __str__(self):
        return self.title
    
    

myblog/blog/forms.py
# form을 장고형식으로 쓰기 위해서(html이 아니라)
# forms.py를 이용해 폼을 생성할 때 반드시 아래 코드 작성
from django import forms
# Post 모델에 대한 폼을 생성하기 위해 Post 모델 로드
from .models import Post

# 모델에서 models.Model를 괄호 안에 넣었듯이
# 폼 생성에서도 class 폼이름(forms.ModelForm):으로 시작해야함
class PostForm(forms.ModelForm):
    
    # 폼의 상세정보 설정을 위해 class Postform 내부에
    # class Meta를 다시 만들어야 함. Meta에 정의한 정보대로 폼이 생성됨.
    class Meta:
        # 이 폼의 타겟이 Post모델(Post모델에 적재 예정), 반드시 model이라는 변수명 쓰기
        model = Post
        # 실제로 사용자에게 입력받을 컬럼은 title과 text만
        # author은 자동으로 계정 연동, create_date는 서버시간
        # published_date는 퍼블리싱할 때 추후 입력
        # pk는 자동으로 글 하나 생성시마다 하나씩 부여
        # 튜플로 입력받을 컬럼 변수명 받음
        fields = ('title', 'text')

myblog/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from blog.models import Post
# 폼작성할 때 로드해야함!
from .forms import PostForm

# 장고 ORM
# 꺼내기 함수 중 create는 적재 함수
# from django.contrib.auth.models import Use
# User.objects.all()로 user 이름 확인
# me = User.objects.get(username='ola')
# Post.objects.create(author=me, title='Sample title', text='Test')
# 작성시간은 디폴드 값으로, 게시시간은 null로 들어감

# Post.objects.filter(author=me)
# filter함수는 용도는 get과 같으나 여러개를 가져올 수 있다. list로 들고옴. 또한 조건을 복잡하게 걸어줄 수 있음
# Post.objects.filter(컬럼명__contains='조건')


# Post.objects.filter(published_date__lte=timezone.now())
# lte는 우측에 있는 시간보다 이전에 있는 것들만 가져옴
# 파이썬은 시간을 초단위로 저장, 기준시간(1970년 1월 1일 00시 00초)을 정하고 1초가 지날 때 마다 1씩 더함
# 크기가 더 작은 게 이전시간 큰게 이후시간이 됨
# 하지만 결과가 안나오죠! 왜??
# published_date에 데이터가 없어서 비교 자체가 안되어서

# post = Post.objects.get(title='안녕하세요 bamtol입니다')
# type(post)
# <class 'blog.models.Post'> Post라는 class타입
# QuerySet : class의 objects들(테이블에서 각 row들의 column들이 list의 요소로 저장됨)

# post.publish() (post 자료형이 Post class니깐!)
# publish 메서드를 사용해서 게시함

# 두 개 이상의 조건 연달아 쓸 수 있음
# Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html',{'posts':posts})

# pk는 우아한 url패턴에서 가져온 것
def post_detail(request, pk):
    # pk에 해당하는 게시판 글은 무조건 1개이므로 get을 쓴다!
    # get_object_or_404는 Post.objects와 같이 쓰이는 함수가 아니라 단독으로 쓰이는 함수!!, 문법 기억해두기
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html',{'post':post})

# post_new는 폼으로 연결해주는 함수이다.
def post_new(request):
    
    # form.py의 method="post"이므로 form을 사용해 들어온 자료는 무조건 post여야함
    # POST방식으로 자료가 들어오는지 검사 -> POST방식으로 들어오면 적재하라!
    # request는 사용자의 요청, method는 요청 방식
    if request.method == "POST":
        form = PostForm(request.POST)
        
        # .is_vaild()는 form에 유효한 값이 들어왔는지를 검사(자료형)
        if form.is_valid():
            # commit은 임시저장 언제든지 롤백할 수 있도록, author와 published_date가 비어있어서 실제 DB에 반영이 안됨
            # 우선 form에서 입력한 title, text 정보를 넘겨받고(pk, crete_date정보는 자동입력)
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            # 모든 컬럼 정보 입력후 이제 저장
            post.save()
            
            # 글 다 썼으면 detail 페이지에서 쓴 글 확인
            # redirect는 특정 페이지로 돌아가라 
            return redirect('post_detail', pk=post.pk)
            
    # get방식으로 들어오는 자료는 무시해야 함: 빈 폼을 저장해라
    else:
        # 만들어놨던 폼 양식을 가져오기 위해서는
        # 변수 = 폼양식()를 써야 한다. ()가 우측에 붙음에 주의.
        # 현재 코드는 PostForm()양식을 따라 만들것임을 보여준다.
        # 깡통 폼
        form = PostForm()

    # 저장한 폼 양식은 템플릿 파일에 같이 넘겨야 한다.
    return render(request, 'blog/post_edit.html', {'form':form})

def post_edit(request, pk):
    # 글을 수정해야 하기 때문에 기존에 입력되어 있던 자료를 가져오는게 먼저임.
    # 개발자 에러페이지가 아니라 사용자 에러 페이지를 띄어줌
    post = get_object_or_404(Post,pk=pk)
    
    # GET방식, POST방식 구분
    # POST는 Form 내부의 submit버튼으로 전송되는 자료, GET은 url로 들어오는 자료(★a태그로 넘어오는 경우)
    # POST 방식은 수정이 완료된 상황을 나타냄!! => 기존 것에 덮어씌어줌
    if request.method == 'POST':
        # POST 방식인 경우는 기존 자료 post에 새로 들어온 정보를 덮어씌움
        form = PostForm(request.POST,instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # 게시시간을 다시 현재 서버시간으로 변경
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail',pk=post.pk)
    
    # get방식으로 들어왔으면 수정 시작
    # db에서 기존 글을 가져와서 PostForm에 기입해둠
    else:
        # 만약 post방식이 아닌 경우라면 get방식 이므로 수정 직전임
        # 따라서 폼으로 다시 연결해줘야함. 이 때의 폼은 수정용 폼이며 수정용 폼에는 기존에 써놨던 글이 먼저 입력되어 있어야 하므로
        # 감안해서 기존 글의 내용이 담겨있는 post를 통해 instance로 넘겨줌
        form = PostForm(instance=post)
    
    return render(request, 'blog/post_edit.html', {'form':form})












myblog/blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<!-- base파일은 항상 띄워지는 파일, %block content%로 감싸서 갈아끼울 내용을 설정!! -->
<!-- head 는 문서 정보를 가지고 있지만, 웹 페이지에서 보이지 않는 정보들을 담는 영역입니다. -->
<!-- 정적파일: CSS와 이미지파일, 컨텐츠가 접속때마다 동일
	  동적파일: 자바스크립트 -->
	  
<!-- static 패키지 내부의 것들을 쓰겠다는 의미! 반드시 적어주기!!-->
{% load static %}

<head>
<meta charset="UTF-8">
<!-- title내부 내용은 tab부분에 띄어줌 -->
<title>장고 blog 연습</title>

<!-- CSS - 부트스트랩 :완성된 CSS 프레임워크 사이트
	인터넷에 있는 파일을 연결 -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<!-- 앞의 rel은 고정문법, 내가 만든 정적파일을 로딩! 이 코드줄은 맨밑에 적어주기, 앞의 코드들 명령에 덮어씌우기 위해서 -->
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
<!-- font 파일 link -->
<link href="https://fonts.googleapis.com/css?family=Amatic+SC|Black+Han+Sans|Josefin+Sans|Nanum+Gothic+Coding|Indie+Flower|Lobster|Lobster+Two|Sigmar+One|Stylish|Sunflower:300|Zhi+Mang+Xing&display=swap" rel="stylesheet"> 

</head>
<!-- body 란 웹 페이지에 직접적으로 보이는 내용이 들어갑니다. 웹 페이지의 내용은 모두 이 body태그안에 들어갑니다. -->
<body>
	
<!-- div는 큼직하게 단위를 나눌 때 씀, p랑 비슷한 역할 -->
<!-- div는 class개념, css파일에서 적용할 때 구분하기 위해서 class이름 적어줌 page-header일 때만 적용해!라는 의미 -->
	<div class ="page-header">
		<!-- top-menu와 glyphicon은 부트스트랩 내부에 있는 것 따로 공부하기, appname 적어주기 'appname:pathname' -->
		<a href="{% url 'blog:post_new' %}" class="top-menu">
			<span class = 'glyphicon glyphicon-plus'></span>
		</a>
		<h1><a href="">Jung Yun's Blog</a></h1><br>
		
	</div>

	
	
	<div class="content container">
	    <div class="row">
	        <div class="col-md-8">
	        	<!-- 모든 page에서 페이지 타이틀은 유지되도록, 내용만 갈아끼우도록 내부만 바뀌도록 함(코드를 단순화 할 수 있음)-->
	        	<!-- block content는 구멍역할 -->
	            {% block content %}
            	{% endblock %}
	        </div>
	    </div>
	</div>
	
	
	
</body>
</html>

myblog/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
	<div class = 'post'>
		{% if post.published_date %}
			<div class='date'>
				{{post.published_date}}
			</div>
		{% endif %}
		<a class="btn btn-default" href ="{% url 'blog:post_edit' pk=post.pk%}">
			<span class="glyphicon glyphicon-pencil"></span>
		</a>
		<h1>{{post.title}}</h1>
		<p>{{post.text|linebreaksbr}}</p>
	</div>
{% endblock %}

myblog/blog/templates/blog/post_edit.html
<!-- 이름 띠가 나타나므로 base파일로 확장 -->
{% extends 'blog/base.html'%}

<!-- 기본적으로 PostForm 양식을 따름, html에서 수정할 양식이 많지 않음 -->

{% block content%}
	<h1>New Post</h1>
	<!-- forms.py의 양식을 이용해 폼을 작성할  때는 action="목적지" 속성은 굳이 입력하지 않아도 된다.-->
	<!-- method는 적어줬지만, 이때 method는 post방식(전송방식 암호화 -> get으로 들어오는 건 받으면 안됨), action은 빠져도 됨! 
	PostForm에서 목적지와 어떤 것을 작성할지 모두 설정해뒀음 -->
	<form method='post' class='post-form'>
		<!-- post방식일 때 반드시 csrf_token을 적어준다. -->
		{% csrf_token %}
		<!-- 양식을 담은 변수이름(view에서 쓴 변수명)이 form이므로 form.as_p 
		다른 이름이라면 양식명.as_p 라고 적는다. -->
		{{form.as_p}}
		
		<!-- 버튼은 작성이 완료되었을 때 자료 제출버튼으로 사용할 것이므로 type=submit, 
		<button>의 여닫는 부분 사이에 적은 문자는 그대로 버튼에 새겨진다.
		class명은 지금 부트스트랩에 있는 것 안적어줘도 됨 -->
		<button type='submit' class='save btn btn-default'>
		SAVE
		</button>
	</form>



{% endblock %}

myblog/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}


<!-- 
<div class = "postlist"> -->
	<!-- 이탤릭체 태그는 em or i, Bold체 태그는 strong or b 
		p tag는 문단표시, 자동으로 줄 바꿈-->
		<!-- 
		<h1>템플릿 추가 완료</h1>
		<p><i><strong>Hi there!</strong></i></p>
		<p><em><b>It works!</b></em></p>
		-->
		
	
		<!-- |linebreaksbr는 웹사이트에 엔터키 반영, 문단으로 나뉨, p태그는 개행태그 -->
		<!-- 
		{%for post in posts%}
			<div class="post">
				<b><h2><a href="">{{post.title}}</a></h2></b><br/>
				<p>{{post.text|linebreaksbr}}</p>
				<p>{{post.published_date}}</p><br/>
			</div>
		{%endfor%}
		
		<div>
			<h2><a href="">My first post</a></h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur venenatis nisi leo, eget consectetur est dignissim vitae. Integer sit amet. </p>
			<p>published: 17.01.2020, 22:58</p>
		</div>
		
		<div>
			<h2><a href="">My second post</a></h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur venenatis nisi leo, eget consectetur est dignissim vitae. Integer sit amet. </p>
			<p>published: 17.01.2020, 22:58</p>
		</div>
</div>
-->
	
	{% block content %}
	<!-- <div class="content container">
	    <div class="row">
	        <div class="col-md-8"> -->
	            {% for post in posts %}
	                <div class="post">
	                    <div class="date">
	                        <p>published: {{ post.published_date }}</p>
	                    </div>
	                    <!-- post_detail이라는 이름의 url에서 pk부분에는 post.pk를 집어넣음 -->
	                    <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
	                    <p>{{ post.text|linebreaksbr }}</p>
	                </div>
	            {% endfor %}
	        <!-- </div>
	    </div>
	</div> -->
	{% endblock %}
	
	